jax-md/jax-md

- jax_md/space.py
- tests/space_test.py
Currently, unwrapped positions are implemented by turning off wrapping in the shift function. Note, that this may cause some subtle numerical accuracy issues in float32 mode and so a more heavyweight solution will be needed if someone relies heavily on unwrapped mode.
Closes #10.
> Adds support for unwrapped positions in spaces.

- jax_md/simulate.py
- tests/simulate_test.py
> Added Langevin integrator + tests.

- jax_md/simulate.py
- tests/simulate_test.py
> Added Brownian dynamics and tests.

- jax_md/smap.py
- tests/smap_test.py
> Improved handling of dynamic potential parameters.

- jax_md/energy.py
- jax_md/quantity.py
- jax_md/simulate.py
- jax_md/space.py
- jax_md/util.py
- tests/quantity_test.py
- tests/space_test.py
> Added pair correction function. Small fix to periodic_general.

- README.md
Small fixes to make the readme snippets run without errors.   With the default 32-bit precision these configurations result in `nan` for the energies, forces and simulated positions (I haven't changed them here)
Thank you for the package, I'm onto small experiments and already appreciating the differentiable `space.py`!
> Fixed readme code snippets

- jax_md/energy.py
> Changed radii -> diameter in harmonic energy docs.

- README.md
- notebooks/customizing_potentials_cookbook.ipynb
Here is the first draft of a tutorial that goes through a bunch of different ways of customizing potentials. There is a section on cell lists and neighbor lists that needs work. 
Comments welcome.
EDIT: I just saw that @sschoenholz added a notebook showing neighbor lists, so maybe it just doesn't belong in this tutorial?
> Add customizing_potentials_cookbook.ipynb

- jax_md/nn.py
Also fix docstring indentation so that the list of arguments
is formatted properly in some functions.
> Fix documented return type of radial symmetry function.

- README.md
- notebooks/implicit_differentiation.ipynb
First shot at a notebook demonstration how to use implicit differentiation for efficiently differentiating through energy minimization routines.
If you have any questions or ideas on how to improve this notebook please don't hesitate to ask me.
> Notebook showing how to use implicit differentiation.

- jax_md/colab_tools/renderer.py
- jax_md/colab_tools/visualization.html
> Add frame rate in colab renderer.

- jax_md/minimize.py
Remove from docstring an arg not existing in the signature.
> Update gradient_descent docstring.

- docs/_static/style.css
- docs/_templates/layout.html
- docs/conf.py
- docs/jax_md.minimize.rst
- docs/jax_md.nn.rst
- docs/jax_md.quantity.rst
- docs/requirements.txt
This PR adds some miscellaneous documentation improvements. In particular, it changes the style to match JAX's new documentation style. It switches from automodule to custom module descriptions for nn.py, minimization.py, and quantity.py.
> Documentation Improvements.

- jax_md/tpu.py
- notebooks/TPU_MD.ipynb
- tests/tpu_test.py
Co-authored-by: Jascha Sohl-Dickstein <jaschasd@google.com>
Co-authored-by: Sam Schoenholz <schsam@google.com>
> Add first version of TPU molecular dynamics code.

- jax_md/minimize.py
- jax_md/rigid_body.py
- jax_md/simulate.py
- tests/rigid_body_test.py
- tests/simulate_test.py
Co-authored-by: Chrisy Xiyu Du <xiyudu@g.harvard.edu>
Co-authored-by: Ella M. King <ellamichelleking@gmail.com>
Co-authored-by: Megan C. Engel <mcengel@ualberta.ca>
Co-authored-by: Ryan Krueger <ryan_krueger@g.harvard.edu>
> Refactor simulation environments to be aligned with Suzuki Trotter decomposition

- notebooks/tutorial/Chapter_3_Neural_Network_Potentials.ipynb
> Created using Colaboratory Link

- notebooks/tutorial/Chapter_3_Neural_Network_Potentials.ipynb
Revert to branch install of jax_md as pypi upgrade does not appear complete. Will revert post-upgrade.
> Created using Colaboratory

- jax_md/energy.py
- tests/energy_test.py
This PR implements the Environment dependent interatomic potential (EDIP). The current parameter values are for Silicon [1,2].
1) Martin Z. Bazant, Efthimios Kaxiras, and J. F. Justo.  "Environment-dependent interatomic potential for bulk silicon". Phys. Rev. B 56, 8542 (1997).
2)  João F. Justo, Martin Z. Bazant, Efthimios Kaxiras, V. V. Bulatov, and Sidney Yip. "Interatomic potential for silicon defects and disordered phases". Phys. Rev. B 58, 2539 (1998).
> Add EDIP potential

- jax_md/dataclasses.py
- jax_md/rigid_body.py
- jax_md/util.py
> add field to dataclasses.py and try to fix #263 to pass test

- README.md
The manuscript on the implementation and usage of JAX-MD RigidBody is finally out! I have added it to the publication section and proposed that this paper be cited for future usage of the RigidBody functionality. 
Let me know what you think!
> Adding new publication to README.md 

- README.md
Hi, thanks for this nice work. I used JAX, M.D. in our paper to generate a benchmark data for particle tracking algorithm, and I would like to add the reference in the README. Thanks!
> Added Laptrack paper in README Publication list
