jax-md/jax-md

jax_md/energy.py, jax_md/smap.py
In google/jax#1229 we tweaked the `eval_shape` API to return both shapes and dtypes. This small PR uses the new API!
=> tweaks for new jax eval_shape api

jax_md/__init__.py, jax_md/colab_tools/__init__.py, jax_md/colab_tools/renderer.py, jax_md/colab_tools/visualization.html
This PR adds a utility to visualize JAX MD simulations inside IPython notebooks. The new functionality is added inside `jax_md.colab_tools.renderer`. To use this functionality, inside a colaboratory notebook write code of the form,
```python
from jax_md.colab_tools import renderer
scene = { 'particles': Sphere(trajectory) }
renderer.render(box_size, scene)
```
=> First pass adding colab visualization code to JAX MD.

jax_md/energy.py
The current version of the Gupta potential lacks a safe sqrt when calculating the attractive term. When distances are larger than cutoff (ex: in bad initializations), this can lead to nans errors.
=> Introduce safe sqrt to Gupta potential

jax_md/nn.py, tests/energy_test.py, tests/nn_test.py
Fixes JAX issue #4881.
Also, fixes the case where `species=None` is passed to BP symmetry functions.
=> Fixed bug when Behler-Parrinello network functions were jit.

jax_md/smap.py, tests/smap_test.py
Introduce a triplet function in smap (extension of pair) that enables functions that operate on three-body interactions (two displacements or distances) to operate on an entire system.
Design decision:
1) Flexibility of parameters sharing ensures that all appropriate parameters are passed to the three body interaction term. Parameters of size 0 and 2 are passed in directly (although the latter has less physical meaning). Parameters of size 1 and 3 are assumed to be defined by the central atom and vmapped over.
2) Maintain a division by 2. after the high precision sum as most three body interaction terms will be symmetric.
=> Introduce triplet function for three-body interactions and associated tests.

notebooks/customizing_potentials_cookbook.ipynb
previous version used a dr_cutoff of 1 regardless of what was passed.
Thanks to @MaxiLechner for pointing this out!
=> fix bug in calculate_bond_data function

jax_md/simulate.py
I notice that there is an inconsistence in the handling of the mass argumento of the init_fn for the npt_nose_hoover simulations. While for the other simulation functions the masses are run through the canonicalize_mass function that call is missing for the npt_nose_hoover. This results in an inconsistence where one can use "row" vectors fr the masses in the other simulation functions but not in the npt_nose_hoover.
The fix consists of adding the very same call to canonicalize_mass that is present in the other simulation functions.
=> Added call to canonicalize_mass in npt_nose_hoover

jax_md/partition.py, setup.py, tests/partition_test.py
Previously, neighbor lists checked to ensure that the number of neighbors per particle did not exceed the maximum allocated capacity. However, neighbor lists use cell lists in an intermediate step to compute the set of neighbors for each particle by looking only in a local region (allowing the algorithm to scale in approximately O(N) time). However, it was possible in some cases for the cell list to overflow without the neighbor list overflowing (as is the case, for example, in #165). 
This PR modernizes the cell list code to mirror the neighbor list implementation (separating the allocation and update)  and adds overflow checking to the cell lists. With this change, the neighbor list code can now check for overflows in the cell list as well.
=> Improve neighbor list overflow checking.

jax_md/partition.py, tests/partition_test.py
=> use int32 for neighbor lists and cell indexes.

jax_md/elasticity.py, jax_md/partition.py, jax_md/quantity.py, jax_md/simulate.py, jax_md/space.py
This PR adds reStructuredText Python code blocks `.. code-block:: python` to correctly render the documentation
=> Fix code blocks and equations in documentation

jax_md/partition.py
It's also consistent with 
```
raise ValueError(('Box must be either: a scalar, a vector, or a matrix. '
f'Found {box}.'))
```
in `space.py`
=> Improve error message of checking `box_size` type

jax_md/util.py
Currently, `util.high_precision_sum` always casts to `jnp.float64`, even if it is summing over an array of integers or complex floats. In this pr, `util.high_precision_sum` using `jnp.issubdtype` to check if the array is any int, float, or complex float, and chooses the proper type to upcast to accordingly. 
To ensure backwards compatibility for weird dtypes, the array is always promoted to float64 unless it is an int or complex float.
=> High precision sum fix

jax_md/quantity.py
This PR adds functionality to calculate volume fractions in arbitrary dimensions. Specifically, it adds the following 4 functions:
- `nball_unit_volume`: calculate the volume of an n-dimensional unit sphere
- `particle_volume`: calculate the total volume of a collection of particles. There are various options for specifying different particle radii (e.g. species, etc.). 
-  `volume_fraction`: calculate the volume fraction, uses `quantity.volume`
- `box_size_at_volume_fraction`: similar to `box_size_at_number_density` but for volume fraction. 
While I did document these functions, a few examples might be useful to explain how to use the parameters `radii`, `particle_count`, and `species` to cover different situations:
- case 1: monodisperse particles
```python
dim = 2
phi = 0.87
radii = 1 …
```
=> add volume fraction functions

jax_md/_nn/e3nn_layer.py
This PR fixes the import for e3nn-jax  `FunctionalFullyConnectedTensorProduct` mentioned in issue #268.
=> Quick fix to e3nn import

.github/workflows/build.yml, jax_md/_nn/e3nn_layer.py, jax_md/_nn/nequip.py, jax_md/partition.py, jax_md/tpu.py, tests/energy_test.py, tests/rigid_body_test.py, tests/tpu_test.py
- Fixed failing build (see [action](https://github.com/MarcBerneman/fix_build/actions/runs/5566807624)) by addressing multiple failing tests.
- Bugfixes (IrrepsArray, imports, function JITs, test tolerances, and memory problems).
- Found some weird bugs in Python tests and thus skipped them (to be investigated further).
- [test_nequip_silicon](https://github.com/jax-md/jax-md/blob/main/tests/energy_test.py#L1047) because the [gnome data](https://github.com/jax-md/jax-md/blob/main/tests/data/nequip_silicon_test/checkpoint_2065) cannot be read anymore and I don't know how it was generated.
- [test_nve_2d_neighbor_list_multi_atom_species](https://github.com/jax-md/jax-md/blob/main/tests/rigid_body_test.py#L271) in rigid_body_test.py, because of a strange dependency on another test. The test …
=> Fix failing build

README.md
There seems to be some old code in the README regarding the allocation of particles using a cell list.
=> Fix legacy neighborhood allocation in README

notebooks/neural_networks.ipynb
The previous data URL `https://aip.scitation.org/doi/suppl/10.1063/1.4990503/suppl_file/supplementary.zip` now seems to lead to an error page, so the notebook as checked in no longer runs.
This change updates the notebook to use the link from the current article page, https://pubs.aip.org/aip/jcp/article/147/2/024104/988620/Representations-in-neural-network-based-empirical. This returns a wrapper zip file containing a `Supplementary.zip` that seems to match the contents of the original `supplementary.zip`, in that with this change the rest of the notebook runs without error.
=> Update broken URL for Cubuk et al. supplementary data.

notebooks/jax_md_cookbook.ipynb
The notebook raises exceptions with the current JAX version (0.4.14, as provided by Colab). This is fixed by making two trivial changes, after which the notebook runs without error:
- Import stax and optimizers from `jax.example_libraries` instead of `jax.experimental`.
- In `plot_system`, the color needs to be manually coerced to an `onp.array` (it is passed in the notebook as a list-of-DeviceArrays, which matplotlib chokes on).
(opening the notebook in Colab also seems to have removed some trailing whitespace, which clutters up the diff - apologies!)
=> Slightly update cookbook notebook to work with recent JAX versions.

jax_md/quantity.py, jax_md/simulate.py, tests/quantity_test.py
=> Revert "Add support for auxiliary data returned by energy/force function"

jax_md/partition.py
Extending partition.py (e.g. NeighborLists) requires visibility to some of the core functionality.
Certain functions ("shift_array" and "unflatten_cell_buffer") would be nice if available in the public interface.
=> Make functions within partition.py public-access for downstream usecases.

jax_md/rigid_body.py
In jax 0.4.24 they removed `KeyArray` from `jax.random` (see https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-24-feb-6-2024), the advice is now to just use `jax.Array` instead.
One line fix.  This closes #298.
=> Fixes #298

jax_md/_nn/e3nn_layer.py, jax_md/_nn/gnome.py, jax_md/_nn/nequip.py, jax_md/partition.py, jax_md/smap.py, jax_md/test_util.py, jax_md/util.py, notebooks/implicit_differentiation.ipynb, tests/elasticity_test.py, tests/energy_test.py, tests/minimize_test.py, tests/nn_test.py, tests/partition_test.py, tests/quantity_test.py, tests/rigid_body_test.py, tests/simulate_test.py, tests/smap_test.py, tests/space_test.py, tests/tpu_test.py
This PR updates the deprecations in jax that are causing warnings or errors on the CI test runs. Specifically:
`from jax.config import config` -> `jax.config`
and 
`jax.tree_map` -> `jax.tree_util.tree_map`
Four of the tests are still failing on my local unit test runs with bool tracer conversion errors. The pytest output for one of the tests is below. If you have some hints at why it's failing, I'll update those as well so the CI should pass.
```python
____________________________________________________________________________ RigidBodyTest.test_nve_2d_neighbor_list_multi_atom_species_dtype=float32 ____________________________________________________________________________
[gw3] linux -- Python 3.9.19 /home/ryan/miniforge3/envs/jax_md/bin/python
jax.errors.SimplifiedTraceback: For …
```
=> Updating tests for deprecations/errors

.github/workflows/build.yml, setup.py, tests/rigid_body_test.py
This pull request fixed the TracerBoolConversionError bug as documented in #277 (clearing the JAX cache between tests seems to be the trick).
Moreover, the minimal Python version was increased to 3.10 to conform to [JAX's minimal version](https://github.com/google/jax/commit/945fde41e49a7cdce67ade1622b706c960120db4).
=> Fix to #277 and update Python version

README.md, jax_md/tpu.py
The following deprecations have been deleted in JAX:
- jax.experimental.maps
- jax.experimental.mesh_utils
Also, I made a minor change in the README
=> Fix JAX deprecations

.github/workflows/build.yml, README.md, setup.py, tests/energy_test.py, tests/quantity_test.py, tests/rigid_body_test.py, tests/simulate_test.py
- [JAX 0.7.0](https://docs.jax.dev/en/latest/changelog.html#jax-0-7-0-july-22-2025) doesn't support Python 3.10 anymore
- dataclasses doesn't need to be in the setup anymore
- Fixed Python tests
There is still an issue in rigid_body_tests.py, where a segmentation error occurs, but I think it's JAX-related. We have to wait and see if this gets fixed.
- Added a publication
- Removed pip install jax-md as the PyPi version is not up-to-date
=> Maintenance + README update
